export const GENERATE_CALENDAR = "GENERATE_CALENDAR";
export const SELECT_DAY = "SELECT_DAY";
export const SELECT_DAY_ERROR = "SELECT_DAY_ERROR";
export const UPDATE_SELECTED_START = "UPDATE_SELECTED_START";
export const UPDATE_SELECTED_FINISH = "UPDATE_SELECTED_FINISH";

export const SELECT_RANGE = "SELECT_RANGE";

export const FETCH_LIFE_TIME_START = "FETCH_LIFE_TIME_START";
export const FETCH_LIFE_TIME_SUCCESS = "FETCH_LIFE_TIME_SUCCESS";   

export const CLEAN_SELECTION = "CLEAN_SELECTION";
export const CLEAN_SUCCESS = "CLEAN_SUCCESS";
export const APPLY_CALENDAR = "APPLY_CALENDAR";

export const CHANGE_SHOWED_MONTH = "CHANGE_SHOWED_MONTH";
export const CHANGE_SHOWED_MONTH_ERROR = "CHANGE_SHOWED_MONTH_ERROR";

export const TOGGLE_POP_UP = "TOGGLE_POP_UP";