export const FETCH_LIFE_TIME_START = 'FETCH_LIFE_TIME_START';
export const FETCH_LIFE_TIME_SUCCESS = 'FETCH_LIFE_TIME_SUCCESS';

export const CLEAN_SELECTION = 'CLEAN_SELECTION';
export const APPLY_CALENDAR = 'APPLY_CALENDAR';

export const TOGGLE_POP_UP = 'TOGGLE_POP_UP';

export const UPDATE_RANGE = 'UPDATE_RANGE';
export const UPDATE_RANGE_ERROR = 'UPDATE_RANGE_ERROR';
export const UDPATE_PREV_RANGE = 'UDPATE_PREV_RANGE';

export const SET_SNIPPET = 'SET_SNIPPET';
